# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_auto_20170509_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=140)),
                ('product_price', models.PositiveIntegerField()),
                ('product_description', models.CharField(max_length=140)),
            ],
        ),
    ]
