# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0004_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
